version: "2.2"
services:
  wpt_server:
    #### python-ssim
    build: 
      context: .
      dockerfile: ./wpt-server/Dockerfile
    image: webpagetest/server:latest
    ports:
      - '4000:80'
    volumes:
      - ./wpt-server/settings/locations.ini:/var/www/html/settings/locations.ini
      - ./wpt-server/settings/settings.ini:/var/www/html/settings/settings.ini
      - ./wpt_data/dat:/var/www/html/dat
      - ./wpt_data/results:/var/www/html/results
      - ./wpt_data/logs:/var/www/html/logs
  wpt_agent:
    build: 
      context: .
      dockerfile: ./wpt-agent/Dockerfile
    image: webpagetest/agent:latest
    cap_add:
    - NET_ADMIN
    network_mode: "host"
    init: true
    privileged: true
    ports:
      - '4001:80'
    environment:
      SERVER_URL: http://localhost:4000/work/
      LOCATION: "Azure Cloud - Linux"
      SHAPER: none
      EXTRA_ARGS: -vvvv --no-sandbox
    depends_on:
      - wpt_server
