version: "3"
services:
  wpt_server:
    #### python-ssim
    build: ./wpt-server/Dockerfile
    container_name: 'webpagetest_server'
    #image: webpagetest/server
    volumes:
      - ./wpt-server/settings/locations.ini:/var/www/html/settings/locations.ini
      - ./wpt-server/settings/settings.ini:/var/www/html/settings/settings.ini
      - ./wpt_data/dat:/var/www/html/dat
      - ./wpt_data/results:/var/www/html/results
      - ./wpt_data/logs:/var/www/html/logs
    ports:
      - 4000:80
  wpt_agent:
    build: ./wpt-agent/Dockerfile
    container_name: 'webpagetest_agent'
    #image: webpagetest/agent:latest
    cap_add:
    - NET_ADMIN
    network_mode: "host"
    environment:
      SERVER_URL: http://localhost:4000/work/
      LOCATION: Linux
    depends_on:
      - wpt_server
